DROP TABLE IF EXISTS hits;

CREATE TABLE IF NOT EXISTS hits
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    app       varchar(200)                                        NOT NULL,
    uri       varchar(200)                                        NOT NULL,
    ip        varchar(15)                                         NOT NULL,
    timestamp TIMESTAMP                                           NOT NULL
);