DROP TABLE IF EXISTS hits_model;

CREATE TABLE IF NOT EXISTS hits_model (
    hit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hit_app varchar,
    hit_uri varchar,
    hit_ip varchar,
    hit_time TIMESTAMP
);