DROP TABLE IF EXISTS users, categories, events, requests, compilations, compilations_events, comments;

CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name  varchar(60)                                         NOT NULL,
    email varchar(60)                                         NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name varchar(60)                                         NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    title              varchar(120)                                        NOT NULL,
    annotation         varchar(2000)                                       NOT NULL,
    description        varchar(7000)                                       NOT NULL,
    participant_limit  INTEGER                                             NOT NULL,
    event_date         timestamp                                           NOT NULL,
    created_on         timestamp                                           NOT NULL,
    published_on       timestamp,
    confirmed_requests INTEGER                                             NOT NULL,
    category           BIGINT                                              NOT NULL REFERENCES categories (id),
    initiator          BIGINT                                              NOT NULL REFERENCES users (id),
    lat                REAL                                                NOT NULL,
    lon                REAL                                                NOT NULL,
    paid               BOOLEAN                                             NOT NULL,
    request_moderation BOOLEAN                                             NOT NULL,
    state              varchar(20)                                         NOT NULL
);

CREATE TABLE IF NOT EXISTS requests
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    event     BIGINT                                              NOT NULL REFERENCES events (id),
    requester BIGINT                                              NOT NULL REFERENCES users (id),
    created   timestamp                                           NOT NULL,
    status    varchar(20)                                         NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    title  varchar(120)                                        NOT NULL,
    pinned BOOLEAN                                             NOT NULL
);

CREATE TABLE IF NOT EXISTS compilations_events
(
    compilation_id BIGINT NOT NULL REFERENCES compilations (id) ON DELETE CASCADE,
    event_id       BIGINT NOT NULL REFERENCES events (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS comments
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    event_id       BIGINT                                              NOT NULL REFERENCES events (id) ON DELETE CASCADE,
    commentator_id BIGINT                                              NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    text           varchar(5000)                                       NOT NULL,
    created        timestamp                                           NOT NULL,
    edited         BOOLEAN                                             NOT NULL
);