version: '3.1'
services:
  stats-server:
    build: stats-service/stats-server
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=ewm-stats
      - DB_HOST=stats-db
      - DB_PORT=5432
      - POSTGRES_USER=ewm-stats
      - POSTGRES_PASSWORD=ewm-stats

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=ewm-stats
      - POSTGRES_PASSWORD=ewm-stats
    volumes:
      - /var/lib/postgresql/data/

  ewm-service:
    build: main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
      - ewm-db

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=ewm-main
      - POSTGRES_PASSWORD=ewm-main
    volumes:
      - /var/lib/postgresql/data/
